import Head from 'next/head' 
import css from 'tailwindcss/tailwind.css'

const posts = [
  {title: 'React Testing', excerpt: 'Learn React Testing'},
  {title: 'React With Tailwind', excerpt: 'Learn React With Tailwind'}
];

export default function Home() {
  return (
    <div className="container mx-auto px-10 mb-8">
      <Head>
        <title>Stack Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className='grid grid-cols-1 lg:grid-cols-12 gap-12 '>
        Hello
        </div>
    </div>
  )
}
